jwt:
  secret: techgeeknext

spring:
  profiles:
    active: default

---

spring:
  profiles: default

  datasource:
    url: jdbc:mysql://54.179.42.252:3306/ecomdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 18Mar#2024
    platform: mysql
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      enabled: true

---

spring:
  profiles: test
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
